package view;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class MainView extends javax.swing.JFrame {

    /** Creates new form MainView */
    public MainView() {
        initComponents();
    }

    public JMenuItem getMenuAdd() {
        return menuAdd;
    }

    public JMenuItem getMenuListar() {
        return menuListar;
    }

    public JMenuItem getMenuSair() {
        return menuSair;
    }

    public JMenuItem getMenuExportar() {
        return menuExportar;
    }

    public JMenuItem getMenuImportar() {
        return menuImportar;
    }

    public JMenuItem getMenuLog() {
        return menuLog;
    }

    public JMenuItem getMenuAddUser() {
        return menuAddUser;
    }

    public JMenuItem getMenuListaUser() {
        return menuListaUser;
    }

    public JMenu getSuperMenuUsuario() {
        return superMenuUsuario;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuImportar = new javax.swing.JMenuItem();
        menuExportar = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuAdd = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenuItem();
        superMenuUsuario = new javax.swing.JMenu();
        menuAddUser = new javax.swing.JMenuItem();
        menuListaUser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuLog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de pessoas");

        jMenu2.setText("Arquivo");

        menuImportar.setText("Importar contatos");
        jMenu2.add(menuImportar);

        menuExportar.setText("Exportar contatos");
        jMenu2.add(menuExportar);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu2.add(menuSair);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Contatos");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menuAdd.setText("Adicionar");
        menuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddActionPerformed(evt);
            }
        });
        jMenu1.add(menuAdd);

        menuListar.setText("Listar pessoas");
        menuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarActionPerformed(evt);
            }
        });
        jMenu1.add(menuListar);

        jMenuBar1.add(jMenu1);

        superMenuUsuario.setText("Usuários");

        menuAddUser.setText("Adicionar");
        superMenuUsuario.add(menuAddUser);

        menuListaUser.setText("Listar");
        superMenuUsuario.add(menuListaUser);

        jMenuBar1.add(superMenuUsuario);

        jMenu3.setText("Configuração");

        menuLog.setText("Log");
        jMenu3.add(menuLog);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void menuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddActionPerformed

    }//GEN-LAST:event_menuAddActionPerformed

    private void menuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuListarActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
    }//GEN-LAST:event_menuSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAdd;
    private javax.swing.JMenuItem menuAddUser;
    private javax.swing.JMenuItem menuExportar;
    private javax.swing.JMenuItem menuImportar;
    private javax.swing.JMenuItem menuListaUser;
    private javax.swing.JMenuItem menuListar;
    private javax.swing.JMenuItem menuLog;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu superMenuUsuario;
    // End of variables declaration//GEN-END:variables

}

